<a href="https://colab.research.google.com/github/pallavi0224/Wine-classification/blob/main/wine_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns


%matplotlib notebook

In [3]:
wine = datasets.load_wine()

In [9]:
df = pd.DataFrame(wine['data'],columns = wine['feature_names'])
df["target"] = wine["target"]
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [10]:
df.shape

(178, 14)

In [11]:
df.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [16]:
X = df
Y = X.pop("target")

In [17]:
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [19]:
X.shape

(178, 13)

In [20]:
Y.unique()

array([0, 1, 2])

In [46]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=55)

In [22]:
X_train.shape

(142, 13)

In [23]:
X_test.shape

(36, 13)

In [27]:
knn = KNeighborsClassifier(n_neighbors=5)

In [28]:
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [29]:
knn.score(X_test,Y_test)

0.6388888888888888

In [45]:
K_range = range(1, 25)
scores = []
for k in K_range:
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train,Y_train)
  scores.append(knn.score(X_test,Y_test)) # Also changed score to scores


plt.figure()
plt.xlabel("K count")
plt.ylabel("Model Accuracy")
plt.scatter(K_range,scores)
plt.grid()
plt.xticks([0, 5, 10, 15, 20, 30])
plt.show()

<IPython.core.display.Javascript object>

In [67]:
test_sizes = [0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1]
knn = KNeighborsClassifier(n_neighbors=5)

plt.figure()

for test_size in test_sizes:
  score = []

  for i in range(1, 100):
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 1 - test_size)
    knn.fit(X_train,Y_train)
    score.append(knn.score(X_test,Y_test))

  plt.plot(test_size, np.mean(score), marker='o') # Changed to plot test_size against mean score


plt.xlabel("Training split %")
plt.ylabel("Accuracy")
plt.show()

<IPython.core.display.Javascript object>

In [68]:
prediction = knn.predict(X_test)
cn = confusion_matrix(Y_test, prediction)

In [53]:
prediction

array([2, 2, 2, 1, 0, 0, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2,
       2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 0, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2,
       0, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 0, 2, 2, 1,
       2, 1, 2, 1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 1, 2, 0, 2, 1, 0, 1, 0, 2,
       2, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0, 2, 0, 0, 1, 2, 1, 0, 2, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 0, 1, 0, 2, 2, 0, 2, 0, 2, 1, 2,
       2, 2, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 2,
       0, 0, 1, 2, 0, 1, 2])

In [54]:
Y_test

60     1
130    2
109    1
92     1
12     0
      ..
131    2
65     1
32     0
97     1
40     0
Name: target, Length: 161, dtype: int64

In [57]:
cm = confusion_matrix(Y_test,prediction)

In [58]:
cm

array([[41,  0, 14],
       [ 1, 43, 20],
       [ 0, 12, 30]])

In [69]:
plt.figure(figsize=(8, 7))
sns.heatmap(cm, annot=True)  # Now sns is defined
plt.title("Confusion Matrix")
plt.ylabel("Truth")
plt.xlabel("Prediction")
plt.show()

<IPython.core.display.Javascript object>